name: Deployment pipeline

on:
  push:
    branches: [main]

  pull_request:
    branches: [main]
    types: [opened, synchronize]

jobs:
  deployment-pipeline:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - uses: actions/setup-node@v1
        with:
          node-version: '14.17.x'

      - name: Install yarn globally
        run: npm install --global yarn

      - name: Install packages
        run: yarn && yarn install:ui

      - name: Lint
        run: yarn lint

      - name: Build
        run: yarn build

      - name: Test
        env:
          TEST_MONGODB_URI: ${{secrets.TEST_MONGODB_URI}}
          SECRET: ${{secrets.SECRET}}
        run: yarn test

      - name: Test:e2e
        env:
          PORT: ${{secrets.PORT}}
          SALT_ROUNDS: ${{secrets.SALT_ROUNDS}}
          SECRET: ${{secrets.SECRET}}
          TEST_MONGODB_URI: ${{secrets.TEST_MONGODB_URI}}
        uses: cypress-io/github-action@v2
        with:
          command: yarn test:e2e
          start: yarn start:test
          wait-on: 'http://localhost:3003'

      - name: Deploy to Heroku
        if: ${{ github.event_name == 'push' && !contains(join(github.event.commits.*.message, ' '), '#skip') }}
        uses: akhileshns/heroku-deploy@v3.12.12
        with:
          heroku_api_key: ${{secrets.HEROKU_API_KEY}}
          heroku_app_name: 'blogapp-552'
          heroku_email: 'olowotemple@yahoo.com'
          healthcheck: 'https://blogapp-552.herokuapp.com/health'
          checkstring: 'ok'
          rollbackonhealthcheckfailed: true

      - uses: actions/checkout@v2
        with:
          fetch-depth: '0'
      - name: Bump version and push tag
        uses: anothrNick/github-tag-action@1.33.0
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          DEFAULT_BUMP: 'patch'

      - name: Slack Success Notification
        uses: 8398a7/action-slack@v3
        with:
          status: custom
          fields: commit,author,took
          custom_payload: |
            {
              attachments: [{
                color: 'good',
                text: `a new version deployed to http://blogapp-552.herokuapp.com/ (${process.env.AS_COMMIT}) by ${process.env.AS_AUTHOR} succeeded in ${process.env.AS_TOOK}`,
              }]
            }
        env:
          SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}
        if: success()

      - name: Slack Failure Notification
        uses: 8398a7/action-slack@v3
        with:
          status: ${{ job.status }}
          fields: repo, commit, took, message, author
        env:
          SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}
        if: failure()
